service: aws-node-http-api
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{any+}
