service: aws-node-http-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
