service: aws-node-http-api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 6
  versionFunctions: false

package:
  excludeDevDependencies: true
  individually: true

functions:
  api:
    handler: src/main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
#    provisionedConcurrency: 10
#    reservedConcurrency: 10

custom:
    optimize:
        external: ['swagger-ui-dist']
