service: aws-node-http-api
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  timeout: 6
  versionFunctions: false
  stage: ${opt:stage, self:custom.default}
  environment:
    NODE_ENV: ${opt:stage, self:custom.default}

package:
  excludeDevDependencies: true
  individually: true

functions:
  api:
    name: ${opt:stage, self:custom.default}-api
    handler: src/main.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

custom:
  dotenv:
    path: environments/${opt:stage, self:custom.default}.env
  optimize:
    external: ['swagger-ui-dist']
  serverlessPluginTypescript:
    tsConfigFileLocation: './tsconfig.build.json'
  default: 'local'
